language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm
before_script:
    - travis_retry composer self-update
    - travis_retry composer install
    - travis_retry composer update
script:
    - vendor/bin/phpunit
after_script:
    - php vendor/bin/codacycoverage clover
    # - php vendor/bin/codacycoverage phpunit build/report.junit.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)